# Generated by Django 5.0.2 on 2024-10-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_alter_startup_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='last_name',
        ),
    ]
