# Generated by Django 5.0.2 on 2024-10-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_rename_first_name_founder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='phase',
            field=models.CharField(blank=True, choices=[('Brainstorming', 'Brainstorming'), ('Fundraising', 'Fundraising'), ('Scaling', 'Scaling'), ('Established', 'Established')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
