# Generated by Django 5.0.2 on 2024-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_alter_startup_phase_alter_startup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
